### PR TITLE
Avoid throwing the spear if sneaking

### PR DESCRIPTION
**Pull request by k1r0s**
This allows for shield usage while having a spear. Maybe we have to specifically check for the shield in the offhand I dunno. Or check the opposite way, only throw the spear while sneaking..

Give me some feedback plz

thx

related: https://github.com/theishiopian/Parrying/issues/13

### CODE REVIEW

**Comment by theishiopian** [comment]
Another solution is to disable throwing with a shield, unless you are sneaking, in which case you throw normally. I think this would be more natural shield wise.

Edit: Oh you suggested that already, I need more sleep...

**Comment by k1r0s** [comment]
> Another solution is to disable throwing with a shield, unless you are sneaking, in which case you throw normally. I think this would be more natural shield wise.
> 
> Edit: Oh you suggested that already, I need more sleep...

yup, I find it more intuitive. Let me handle it

**Comment by k1r0s** [comment]
just to make it clear, to me, having a weapon (spear) in the main hand while holding something in the off hand, the intuitive behavior to use the offhand item by default. So in the code first we have to check whether offhand is empty or not before checking if the user is sneaking

**Comment by k1r0s** [comment]
Please @theishiopian check this behavior

**Comment by theishiopian** [comment]
Thank you, I will review this soon

**Comment by theishiopian** [comment]
This has been implemented in the 1.18 branch, and applied to daggers

**Pull request closed without merging**
